import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import { data } from 'data';
import Link from 'next/link';
export default function Home() {
  return (
    <div className="py-3">
      <Head>
        <title>Hodace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://chungcueratown.net/wp-content/uploads/2015/11/icon-bds.jpg" />
        <meta name="description" content="Hodace địch vụ bất động sản"/>
        <meta property="og:image" content="https://vnn-imgs-f.vgcloud.vn/2019/07/08/06/om-mong-lam-giau-tu-bat-dong-san-can-than-tien-mat-tat-mang.jpg" />
      </Head>
      <div className="max-w-7xl mx-auto">
        <div className="des-i mages mt-5 grid grid-cols-3 gap-16 p-10">
          {data.map(item => (
            <Link key={item.id} href={`/${item.id}`}>
              <a>
                <div className="card rounded-2xl overflow-hidden relative w-full h-[200px] ">
                  <Image src={item.img} alt="" layout="fill" className="w-full" />
                </div>
                <h4 className="font-bold px-4">{item.title}</h4>
              </a>
            </Link>
          ))}

        </div>
      </div>
    </div>
  );
}
